Comments:
  - Scenario 2

Network:
  filename: L-TOWN_Real.inp

results_path: Scenario2//

times:
  StartTime: 2019-01-01 00:00
  EndTime: 2019-02-28 23:55

leakages:
- # linkID, startTime, endTime, leakDiameter (m), leakType, peakTime
- p101, 2019-01-03 20:05, 2019-02-28 23:55, 0.011906, incipient, 2019-02-28 22:10
- p413, 2019-02-10 13:25, 2019-02-28 23:55, 0.015008, abrupt, 2019-02-10 13:25
- p805, 2019-02-10 11:55, 2019-02-20 23:55, 0.013195, incipient, 2019-02-20 23:55


outages:
- StartTime: 2019-01-02 00:00
  EndTime: 2019-01-02 23:55


pump_curves:
- StartTime: 2019-02-22 00:00
  EndTime: 2019-02-28 23:55
  curve: [[0.0, 70], [0.007607111111111111, 40], [0.013888611111111112, 0.0]]


pump_control_low:
  StartTime: 2019-01-15 00:00
  EndTime: 2019-01-22 23:55
  value: 1.5

masking_pressure:
  - StartTime: 2019-01-15 00:00
    EndTime: 2019-01-22 23:55
    node: T1

pressure_sensors:
- n1
- n4
- n31
- n54
- n105
- n114
- n163
- n188
- n215
- n229
- n288
- n296
- n332
- n342
- n410
- n415
- n429
- n458
- n469
- n495
- n506
- n516
- n519
- n549
- n613
- n636
- n644
- n679
- n722
- n726
- n740
- n752
- n769

flow_sensors:
- PUMP_1
- p227
- p235

level_sensors:
- T1

amrs:
- n1
- n2
- n3
- n4
- n6
- n7
- n8
- n9
- n10
- n11
- n13
- n16
- n17
- n18
- n19
- n20
- n21
- n22
- n23
- n24
- n25
- n26
- n27
- n28
- n29
- n30
- n31
- n32
- n33
- n34
- n35
- n36
- n39
- n40
- n41
- n42
- n43
- n44
- n45
- n343
- n344
- n345
- n346
- n347
- n349
- n350
- n351
- n352
- n353
- n354
- n355
- n356
- n357
- n358
- n360
- n361
- n362
- n364
- n365
- n366
- n367
- n368
- n369
- n370
- n371
- n372
- n373
- n374
- n375
- n376
- n377
- n378
- n379
- n381
- n382
- n383
- n384
- n385
- n386
- n387
- n388
- n389